import Head from 'next/head'
import MenuLayout from '../../components/MenuLayout'
import React, { useEffect, useState } from 'react'
import toast from "react-hot-toast";
import { Box, Button, Center, Flex, Img, Input, Spinner } from '@chakra-ui/react';
import Image from 'next/image';
import { COLORS } from '../../services/theme/colors';
import ProductDisplay from '../../components/homepagecomponents/Electronics/ProductDisplay';
import Lottie from 'react-lottie';
import Empty from '../../assets/lottie/empty.json'
import { getSearchResult } from '../../services/productService';
import { useRouter } from 'next/router';

export default function Arrival() {

    const [data, setData] = useState([]);
    const [value, setValue] = useState("")
    const [loading, setLoading] = useState(false)
    const { query } = useRouter()
    const defaultOptions = {
        loop: true,
        autoplay: true,
        animationData: Empty,
        rendererSettings: {
            preserveAspectRatio: 'xMidYMid slice'
        }
    };

    async function SearchProduct() {
        setLoading(true);
        const result = await getSearchResult(value)
        setData(result)
        setLoading(false)
        console.log(data, "result")
    }

    useEffect(() => {
        SearchProduct()
    }, [])

    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="theme-color" content="#0dadf7" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Box bg={COLORS.white}>
                    <MenuLayout menu={false} category={false}>
                        <Box p={["20px", "20px", "20px", "30px"]} fontWeight="800" fontSize={["30px", "30px", "30px", "60px"]}>
                            New Arrival Product
                        </Box>
                        <Center bg="rgba(217, 217, 217, 0.2)" pt="20px" pb="20px">
                            <Flex justifyContent={["space-between", "space-between", "space-between", "flex-start"]} flexWrap="wrap">
                                {loading ?
                                    <Center h="300px" w="full">
                                        <Spinner size="xl" />
                                    </Center> :
                                    data.length < 1 ?
                                        <Center flexDir="column" p="20px" w="full">
                                            <Lottie options={defaultOptions}
                                                height={300}
                                                width={300} />
                                            <Box fontWeight="700" mt="10px" fontSize="24px">
                                                No Result
                                            </Box>
                                        </Center>
                                        :
                                        data?.map((item: any, index: number) => {
                                            return (
                                                <Box key={index} mb="20px">
                                                    <ProductDisplay item={item} index={index} />
                                                </Box>
                                            )
                                        })}
                            </Flex>
                        </Center>
                    </MenuLayout>
                </Box>
            </main>
        </>
    )
}
