export const england = [
    "London",
    "Birmingham",
    "Manchester",
    "Leeds",
    "Sheffield",
    "Liverpool",
    "Bristol",
    "Newcastle upon Tyne",
    "Nottingham",
    "Southampton",
    "Derby",
    "Coventry",
    "Leicester",
    "York",
    "Cambridge",
    "Oxford",
    "Norwich",
    "Wakefield",
    "Lichfield",
    "Carlisle",
    "Exeter",
    "Chester",
    "St Albans",
    "Sunderland",
    "Plymouth",
    "Hull",
    "Blackpool",
    "Middlesbrough",
    "Sunderland",
    "Watfor"
]