import Head from 'next/head'
import MenuLayout from '../components/MenuLayout'
import React, { useEffect } from 'react'
import toast from "react-hot-toast";
import ContactForm from '../components/homepagecomponents/ContactForm'
import ContactFaq from '../components/homepagecomponents/ContactFaq'
import { Box } from '@chakra-ui/react';

export default function Home() {

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#0dadf7" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box bg={"#FFF"}>
        <MenuLayout menu={false} category={false}>
            <ContactForm />
        </MenuLayout>
        </Box>
      </main>
    </>
  )
}
